name: Christoph Burkhardt
favicon: null
layout_spectrum: 0
typography_spectrum: 0.46519
title: How to change the world
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eeeeee'
    - '#070707'
    - '#cbcbcb'
    - '#65666a'
    - '#919191'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
