name: Christoph Burkhardt
favicon: null
layout_spectrum: 0.9545977446250618
typography_spectrum: 0.4440713233780116
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.125
  lightness: 1
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
